# Object in Python

* Everything is an object
* We can create our own objects

In [177]:
import math
class Complex:
    def __init__(self, real_part, imaginary_part):
        self.re = real_part
        self.im = imaginary_part
#        self.norm = math.sqrt(real_part**2 + imaginary_part**2)
        
    @classmethod
    def from_polar(cls, r, theta):
        return cls(r*math.cos(theta), r*math.sin(theta))
    
    def conjugate(self):
        return Complex(self.re, -self.im)

    @property
    def norm(self):
        return math.sqrt(self.re**2 + self.im**2)
    
    @property
    def theta(self):
        return math.atan2(self.im, self.re)
    
    def __str__(self):
        if self.im==0:
            return f"{self.re}"
        if self.re==0:
            return f"{self.im}J"
        if self.im<0:
            return f"{self.re} - {-self.im}J"
        return f"{self.re} + {self.im}J"
    
    def __repr__(self):
        return f"Complex({self.re}, {self.im})"

    @staticmethod
    def _try_to_convert_other_to_complex(other):
        if isinstance(other, (int, float)):
            return  Complex(other, 0)
        return other
    
    def __add__(self, other):
        other = self._try_to_convert_other_to_complex(other)
        if isinstance(other, Complex):
            return Complex(self.re + other.re, self.im + other.im)
        return NotImplemented
    
    def __radd__(self, other):
        return self + other
        
    def __sub__(self, other):
        other = self._try_to_convert_other_to_complex(other)
        if isinstance(other, Complex):
            return Complex(self.re - other.re, self.im - other.im)
        return NotImplemented
    
    def __mul__(self, other):
        other = self._try_to_convert_other_to_complex(other)
        if isinstance(other, Complex):
            return Complex.from_polar(self.norm*other.norm, self.theta + other.theta)
        return NotImplemented

    def __truediv__(self, other):
        other = self._try_to_convert_other_to_complex(other)
        if isinstance(other, Complex):
            return Complex.from_polar(self.norm/other.norm, self.theta - other.theta)
        return NotImplemented

            
    def __rsub__(self, other):    
        return -self + other
    
    def __neg__(self):
        return Complex(-self.re, -self.im)

In [178]:
z1 = Complex(1, 2)
z2 = Complex(.34, 1.2)
z1 / z2

Complex(1.761378246335819, -0.33427616353818485)

In [181]:
1//2

0

In [171]:
Complex.from_polar(1, math.pi/4)

Complex(0.7071067811865476, 0.7071067811865475)

In [151]:
z1.theta

1.1071487177940904

In [152]:
Complex(-1, -2).theta

-2.0344439357957027

In [153]:
Complex(0, -2).theta

-1.5707963267948966

In [128]:
-z1

Complex(-1, -2)

In [129]:
z1 = z.conjugate()
print(z1)


1 - 2J


In [53]:
z.conjugate()

In [48]:
import numpy as np

a = np.arange(3)
print(a)

[0 1 2]


In [49]:
a

array([0, 1, 2])

In [50]:
np.array([0, 1, 2])

array([0, 1, 2])

In [51]:
a.__str__()

'[0 1 2]'

In [52]:
a.__repr__()

'array([0, 1, 2])'

In [167]:
class Test:
    a = 1
    b = []
    
    def f(self, x):
        return self.a + x
    
    @classmethod
    def f(cls, c):
        print(c)
        print(cls)
    
t1 = Test()
t2 = Test()

print(t1.a)
t1.a = 3
t2.a

t1.b.append(3)
print(t2.b)

1
[3]


In [168]:
Test.f(1)

1
<class '__main__.Test'>


In [163]:
Test.a

1

In [164]:
type(Test)

type

In [47]:
z

In [18]:
z.conjugate

<bound method Complex.conjugate of <__main__.Complex object at 0x7f26223d2460>>

In [119]:
def my_decorator(initial_function):
    def new_function(*args, **kwd):
        print('Hello')
        print(args)
        print(kwd)
        return initial_function(*args, **kwd)
    return new_function

def f(x, y):
    return x + y

f(1, 2)

f = my_decorator(f)
f(1, 2)

Hello
(1, 2)
{}


3

In [120]:
@my_decorator
def f(x, y):
    return x + y



In [121]:
import numpy as np

@np.vectorize
def my_abs(x):
    if x>0:
        return x
    else:
        return -x
    
my_abs(np.random.normal(size=10))

array([0.14340163, 0.0224745 , 1.02887805, 1.04111045, 1.07571282,
       0.91169303, 0.52630414, 0.23115777, 0.05034749, 0.31510264])

In [122]:
def check_args_are_int(initial_function):
    def new_function(*args):
        for arg in args:
            if not isinstance(arg, int):
                raise Exception('Arguments are not integers')
        return initial_function(*args)
    return new_function

@check_args_are_int
def f(x, y):
    return x + y

f(1, 2)

3

In [123]:
f(1.2, 4)

Exception: Arguments are not integers

In [132]:
def multiplication(a, b):
    out = a.__mul__(b)
    if out!=NotImplemented:
        return out
    out = b.__rmul__(a)
    if out!=NotImplemented:
        return out
    raise Exception('Cannot multipliy {} by {}'.format(type(a), type(b))
                   )
    

In [137]:
multiplication(z, z.conjugate())

Complex(10, 0)

### Special methods

* `__init__`
* `__repr__`, `__str__`


Unary and binary operator
* `__neg__`
* `__add__`, `__sub__`, `__mul__`, `__truediv__`, `__mod__`, `__pow__`, `__matmul__`
* `__radd__`, ...
* `__eq__` (==), `__ne__` (!=), `__lt__` (<), `__le__` (<=), `__gt__`, `__ge__`
* `__or__`, `__and__`, `__xor__`


Containers emulation
* a[key] => `a.__getitem__(key)`
* a[key] = val => `a.__setitem__(key, val)`
* del a[key] => `a.__delitem__(key)`
* len(a) => `a.__len__()`
* for elm in a => `for elm in a.__iter__()`

### Attributes and property
* Class attributes and object attributes
* property

### Heritage
* isinstance 

### Dataclasses
* Object with atributes set automatically in the ``__init__`` : https://docs.python.org/3/library/dataclasses.html

In [196]:
import dataclasses

@dataclasses.dataclass
class MyClass(object):
    a : int 
    b : float 

c = MyClass(1, 3.14)

c

MyClass(a=1, b=3.14)

In [191]:
def f(x : int, y : float, z):
    y : complex = 4
    return 2*x

In [192]:
f.__annotations__

{'x': int, 'y': float}

In [193]:
MyClass.__annotations__

{'a': int, 'b': float}