# Numpy
## Examples
* Why numpy? data type

## Array creation 
* array :  from a list
* zeros, ones, eye
* arange
* linspace, logspace
* np.random.rand, ...

## Usefull functions
* ufunc / vectorize command
* methods/ numpy functions (max, min, mean, std, sort, ...)


In [8]:
import numpy as np

a = np.array([4, 2, 4])
b = np.array([45, 2, 7])
c = np.array([1, 2, 5, 67])
a + 5
a/b

array([0.08888889, 1.        , 0.57142857])

In [6]:
np.sin(a)

array([-0.7568025 ,  0.90929743, -0.7568025 ])

In [7]:
from math import sin
sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [9]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [12]:
a = np.array([4, 2, 4])
a.dtype

dtype('int64')

In [17]:
a[1] = 5.9J
a

TypeError: can't convert complex to int

In [18]:
len(a)

3

In [19]:
a.size

3

In [20]:
np.array([1, 2, 5], dtype='float')


array([1., 2., 5.])

In [22]:
np.zeros(10, dtype='complex')

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j, 0.+0.j])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.arange(4, 10, 2)

array([4, 6, 8])

In [28]:
N = 10
np.arange(N)/N

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [31]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [32]:
a = 0
b = 1
N = 10
dx = (b - a)/N
np.arange(N)*dx + a

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
np.linspace(0, 2, 10, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [34]:
np.logspace(0, 3)

array([   1.        ,    1.1513954 ,    1.32571137,    1.52641797,
          1.75751062,    2.02358965,    2.32995181,    2.6826958 ,
          3.0888436 ,    3.55648031,    4.09491506,    4.71486636,
          5.42867544,    6.25055193,    7.19685673,    8.28642773,
          9.54095476,   10.98541142,   12.64855217,   14.56348478,
         16.76832937,   19.30697729,   22.22996483,   25.59547923,
         29.47051703,   33.93221772,   39.06939937,   44.98432669,
         51.79474679,   59.63623317,   68.6648845 ,   79.06043211,
         91.0298178 ,  104.81131342,  120.67926406,  138.94954944,
        159.98587196,  184.20699693,  212.09508879,  244.20530945,
        281.1768698 ,  323.74575428,  372.75937203,  429.19342601,
        494.17133613,  568.9866029 ,  655.12855686,  754.31200634,
        868.51137375, 1000.        ])

In [35]:
np.random.rand(10)

array([0.40712653, 0.03322509, 0.53713415, 0.94661544, 0.9296627 ,
       0.76120046, 0.05012845, 0.28994128, 0.18463291, 0.18279878])

In [37]:
np.random.normal(size=10)

array([ 0.85651811, -1.85117501, -0.17200271,  0.10359099,  0.32695487,
       -0.09743411,  1.44448999,  0.13979669, -0.7219485 ,  0.89677792])

In [39]:
np.arcsin(np.random.rand(10))

array([0.4530352 , 1.38799019, 0.07380742, 0.88506539, 1.15584489,
       0.07761778, 1.13889577, 0.04126331, 0.6295135 , 0.05361399])

In [43]:
a = np.random.normal(size=1000)

np.mean(a)
np.std(a)
np.var(a)
np.sum(a)
np.prod(a)
np.min(a)
np.max(a)

3.3943226058825853

In [44]:
a = np.random.normal(size=10)
print(a)

np.argmax(a)

[ 1.17489359  0.43515666  1.26900821 -0.22609801  0.06661361  0.09031438
 -0.62387328 -0.96563062 -0.19000319 -1.5480428 ]


2

In [45]:
np.sort(a)

array([-1.5480428 , -0.96563062, -0.62387328, -0.22609801, -0.19000319,
        0.06661361,  0.09031438,  0.43515666,  1.17489359,  1.26900821])

In [47]:
np.argsort(a)

array([9, 7, 6, 3, 8, 4, 5, 1, 0, 2])

In [51]:
def lorentz(x):
    return 1/(1 + x**2)

def gaussian(x):
    return np.exp(-x**2)

lorentz(a)
gaussian(a)

array([0.25148424, 0.82748747, 0.1998113 , 0.95016435, 0.99557246,
       0.99187649, 0.67758663, 0.39359119, 0.96454266, 0.0910418 ])

In [52]:
def func(x, y):
    return x + y

func('Bonjour', 'Hello')

'BonjourHello'

In [58]:
def my_abs_scalar(x):
    if x>0:
        return x
    else:
        return -x
    
def my_abs_array(x):
    N = len(x)
    output = np.zeros(N)
    for i in range(N):
        output[i] = my_abs_scalar(x[i])
    return output
    
my_abs(-4)

4

In [59]:
a = np.array([1, 4, -1])

my_abs_array(a)

array([1., 4., 1.])

In [55]:
a>0

array([ True,  True, False])

In [60]:
def convert_scalar_function_to_array_function(scalar_function):
    def array_function(x):
        N = len(x)
        output = np.zeros(N)
        for i in range(N):
            output[i] = scalar_function(x[i])
        return output
    return array_function

my_abs_array = convert_scalar_function_to_array_function(my_abs_scalar)

my_abs_array(a)

array([1., 4., 1.])

In [61]:
my_abs_array = np.vectorize(my_abs_scalar)
my_abs_array(a)

array([1, 4, 1])

## getitem et setitem
* indices
* slices
* Booleans array

In [67]:
a = np.random.rand(10)
print(a)

a[::3]

[0.60010653 0.53001083 0.1566845  0.96145763 0.66917431 0.84032189
 0.98578072 0.67287351 0.12993616 0.49305895]


array([0.60010653, 0.96145763, 0.98578072, 0.49305895])

In [68]:
a[::2] = 0
a

array([0.        , 0.53001083, 0.        , 0.96145763, 0.        ,
       0.84032189, 0.        , 0.67287351, 0.        , 0.49305895])

In [69]:
a[::2] = np.random.normal(5)
a

array([4.9624836 , 0.53001083, 4.9624836 , 0.96145763, 4.9624836 ,
       0.84032189, 4.9624836 , 0.67287351, 4.9624836 , 0.49305895])

In [72]:
N = 10
a = np.random.rand(N)
b = np.random.normal(size=N)

the_slice = slice(None, None, 2)
a[the_slice] = b[the_slice]



In [74]:
a = np.random.rand(N)
print(a)

indices = np.array([1, 4])
a[indices]

[0.35967877 0.89719595 0.75768138 0.17710004 0.25874021 0.72888711
 0.16924651 0.51108768 0.6472195  0.77282355]


array([0.89719595, 0.25874021])

In [77]:
np.sort(a)[-3:]

array([0.75768138, 0.77282355, 0.89719595])

In [78]:
a[np.argsort(a)[:3]]

array([0.16924651, 0.17710004, 0.25874021])

In [79]:
a = np.arange(5)

mask = np.array([True, True, False, False, True])

a[mask]


array([0, 1, 4])

In [80]:
a[mask] = 10
a

array([10, 10,  2,  3, 10])

In [82]:
a = np.random.normal(size=10)
print(a)
a>0

[-0.19102433 -0.96668513  1.47153248 -0.08141159  0.13073803 -1.15939667
 -0.70365675  0.10261223 -0.57046722  0.80049226]


array([False, False,  True, False,  True, False, False,  True, False,
        True])

In [84]:
a[a<0] = 0
a

array([0.        , 0.        , 1.47153248, 0.        , 0.13073803,
       0.        , 0.        , 0.10261223, 0.        , 0.80049226])

In [86]:
a = np.random.normal(size=10)
print(a)
a[a<0] = -a[a<0]
a

[-1.62930427 -1.46231613 -1.01454156 -0.09357848  0.22659914 -0.34171939
 -0.0058308   0.70581585 -1.58653412 -1.34484019]


array([1.62930427, 1.46231613, 1.01454156, 0.09357848, 0.22659914,
       0.34171939, 0.0058308 , 0.70581585, 1.58653412, 1.34484019])

In [87]:
def my_abs_numpy(x):
    output = x.copy()
    output[output<0] = -output[output<0]
    return output

a = np.random.normal(size=10)
my_abs_numpy(a)

array([8.92302165e-01, 1.13244879e-01, 1.41138817e-03, 1.14811804e-01,
       3.14240842e-01, 1.74918045e+00, 1.42738105e+00, 5.78713760e-01,
       3.08452049e-01, 1.58265160e-01])

In [88]:
a = np.random.normal(size=10000000)

In [92]:
def my_abs_numpy(x):
    output = x.copy()
    mask = output<0
    output[mask] = -output[mask]
    return output


In [93]:
%timeit my_abs_numpy(a)

134 ms ± 356 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [90]:
%timeit np.abs(a)

22.5 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [91]:
%timeit my_abs_array(a)

1.26 s ± 4.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 2D arrays (and nD)
* meshgrid, indices, fromfunction
* methods/numpy functions
* linear algebra, matrices

In [96]:
a = np.array([[1, 3, 6], [2, 5, 9]])
a

array([[1, 3, 6],
       [2, 5, 9]])

In [103]:
a[(1, 2)]

9

In [104]:
l = [[1, 3, 6], [2, 5, 9]]
l[1][2]
a[1][2]

9

In [107]:
a[1, 1:]

array([5, 9])

In [108]:
np.meshgrid?

In [111]:
X, Y = np.meshgrid([0, 1, 2, 3], [0.1, 0.2, 0.3])

X, Y

(array([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]]),
 array([[0.1, 0.1, 0.1, 0.1],
        [0.2, 0.2, 0.2, 0.2],
        [0.3, 0.3, 0.3, 0.3]]))

In [114]:
X, Y = np.meshgrid(np.linspace(-1, 1, num=3),np.linspace(-1, 1, num=5) )
X**2 + Y**2

array([[2.  , 1.  , 2.  ],
       [1.25, 0.25, 1.25],
       [1.  , 0.  , 1.  ],
       [1.25, 0.25, 1.25],
       [2.  , 1.  , 2.  ]])

In [121]:
a = np.random.rand(5, 3)*20
a

array([[ 8.77574569,  3.83115674, 10.61605734],
       [ 5.59343819, 13.82380624, 14.73993406],
       [13.6550769 , 18.79519464, 10.26816692],
       [ 4.86162557,  1.60041825, 14.87891592],
       [15.27016478,  8.87530778, 14.74844005]])

In [118]:
a[:,0]
a[1, :]

array([0.25532188, 0.86948659, 0.96522715])

In [122]:
a.mean(axis=0)

array([ 9.63121023,  9.38517673, 13.05030286])

In [123]:
a.mean(axis=1)

array([ 7.74098659, 11.38572616, 14.23947948,  7.11365325, 12.96463753])

## Saving/reading Numpy array
* ASCII (libre office)
* Binary

## Inside numpy array
* data, shape, strides
* Broadcast